Repository hitachienergy/epiphany, pull requests merged in 2019-03, with the labels that each got.

#151 Item: #0000 Desc: Add port to python3 of template_engine
  core/src/core/template_engine_3
Labels: type/feature

#152 Added smoke tests for logging
  core/core/test/serverspec/spec/elasticsearch-curator/elasticsearch-curator_spec.rb
  core/core/test/serverspec/spec/elasticsearch/elasticsearch_spec.rb
  core/core/test/serverspec/spec/filebeat/filebeat_spec.rb
  core/core/test/serverspec/spec/kibana/kibana_spec.rb
  core/core/test/serverspec/spec/spec_helper.rb
Labels: area/logs

#158 Added smoke tests for monitoring
  core/core/test/serverspec/spec/grafana/grafana_spec.rb
  core/core/test/serverspec/spec/node_exporter/node_exporter_spec.rb
  core/core/test/serverspec/spec/prometheus/prometheus_spec.rb
  core/core/test/serverspec/spec/spec_helper.rb
Labels: area/monitoring
