Repository hitachienergy/epiphany, pull requests merged in 2021-05, with the labels that each got.

#2285 Fix automated tests for upgrade mode
  CHANGELOG-1.0.md
  core/src/epicli/data/common/tests/spec/filebeat/filebeat_spec.rb
  core/src/epicli/data/common/tests/spec/kibana/kibana_spec.rb
  core/src/epicli/data/common/tests/spec/logging/logging_spec.rb
  core/src/epicli/data/common/tests/spec/prometheus/prometheus_spec.rb
Labels: type/backport

#2298 Fix PostgreSQL automated tests for single machine installation
  CHANGELOG-1.0.md
  core/src/epicli/data/common/tests/spec/postgresql/postgresql_spec.rb
  core/src/epicli/data/common/tests/spec/spec_helper.rb
Labels: area/testing, type/backport

#2296 Fix PostgreSQL automated tests for single machine installation
  CHANGELOG-1.1.md
  core/src/epicli/data/common/tests/spec/postgresql/postgresql_spec.rb
  core/src/epicli/data/common/tests/spec/spec_helper.rb
Labels: area/testing

#2317 [Backport][0.7] Pgpool not showing Replication State
  CHANGELOG-0.7.md
  core/src/epicli/data/common/ansible/playbooks/postgresql.yml
  core/src/epicli/data/common/ansible/playbooks/roles/applications/templates/pgpool/configmaps.yml.j2
  core/src/epicli/data/common/ansible/playbooks/roles/postgresql/defaults/main.yml
  core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/configure-postgresql.yml
  core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/replication-repmgr-Debian.yml
  core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/replication-repmgr-RedHat.yml
  docs/home/howto/DATABASES.md
Labels: type/backport

#2340 Fix non-clustered mode for Elasticsearch
  CHANGELOG-1.1.md
  core/src/epicli/data/common/ansible/playbooks/roles/opendistro_for_elasticsearch/templates/elasticsearch.yml.j2
Labels: area/logs
