Repository hitachienergy/epiphany, pull requests merged in 2021-02, with the labels that each got.

#2018 [Backport] Upgrade Docker to v19.03.14
  CHANGELOG-0.8.md
  core/src/epicli/data/common/ansible/playbooks/roles/docker/defaults/main.yml
  core/src/epicli/data/common/ansible/playbooks/roles/docker/tasks/configure-docker.yml
  core/src/epicli/data/common/ansible/playbooks/roles/docker/tasks/main.yml
  core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/centos-7/requirements.txt
  core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/redhat-7/requirements.txt
  core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/ubuntu-18.04/requirements.txt
  core/src/epicli/data/common/ansible/playbooks/roles/upgrade/tasks/kubernetes/upgrade-master0.yml
  docs/home/COMPONENTS.md
  docs/home/HOWTO.md
  docs/home/howto/MODULES.md
Labels: type/backport

#2015 [v0.8] Fix automated tests for Zookeeper
  core/src/epicli/data/common/ansible/playbooks/roles/zookeeper/tasks/main.yml
  core/src/epicli/data/common/ansible/playbooks/roles/zookeeper/templates/zoo.cfg.j2
  core/src/epicli/data/common/ansible/playbooks/roles/zookeeper/templates/zoo.j2
  core/src/epicli/data/common/defaults/configuration/zookeeper.yml
  core/src/epicli/data/common/tests/spec/kafka/kafka_spec.rb
  core/src/epicli/data/common/tests/spec/zookeeper/zookeeper_helpers.rb
  core/src/epicli/data/common/tests/spec/zookeeper/zookeeper_spec.rb
Labels: area/kafka, area/testing, type/backport

#2019 [Backport] Patching cgroup drivers
  CHANGELOG-0.8.md
  core/src/epicli/data/common/ansible/playbooks/roles/docker/defaults/main.yml
  core/src/epicli/data/common/ansible/playbooks/roles/docker/handlers/main.yml
  core/src/epicli/data/common/ansible/playbooks/roles/docker/tasks/configure-docker.yml
  core/src/epicli/data/common/ansible/playbooks/roles/docker/tasks/update-daemon-config.yml
  core/src/epicli/data/common/ansible/playbooks/roles/docker/templates/daemon.json.j2
  core/src/epicli/data/common/ansible/playbooks/roles/kubernetes_common/tasks/configure-kubelet.yml
  core/src/epicli/data/common/ansible/playbooks/roles/upgrade/tasks/kubernetes/patch-cgroup-driver.yml
  core/src/epicli/data/common/ansible/playbooks/roles/upgrade/tasks/kubernetes/upgrade-master0.yml
  core/src/epicli/data/common/ansible/playbooks/roles/upgrade/tasks/kubernetes/upgrade-masterN.yml
  core/src/epicli/data/common/ansible/playbooks/roles/upgrade/tasks/kubernetes/upgrade-node.yml
  core/src/epicli/data/common/ansible/playbooks/roles/upgrade/tasks/kubernetes/utils/restart-kubelet-and-docker.yml
Labels: type/backport

#2007 [Backport] RabbitMQ 3.8.9 upgrade
  CHANGELOG-0.8.md
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/defaults/main.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/Debian.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/RedHat.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/configure-policies.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/configure-rabbitmq.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/cookie-setup/master.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/cookie-setup/nodes.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/enable-and-start-service.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/install-packages-debian.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/install-packages-redhat.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/join-cluster.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/main.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/set-erlang-cookie.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/set-logrotate.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/set-ulimits.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/set-variables.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/update-erlang-cookie.yml
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/templates/erlang-cookie.j2
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/templates/logrotate-config.j2
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/templates/rabbitmq-env.conf.j2
  core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/templates/rabbitmq-server.j2
  core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/centos-7/requirements.txt
  core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/redhat-7/requirements.txt
  core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/ubuntu-18.04/add-repositories.sh
  core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/ubuntu-18.04/requirements.txt
  core/src/epicli/data/common/ansible/playbooks/roles/upgrade/tasks/rabbitmq.yml
  core/src/epicli/data/common/ansible/playbooks/upgrade.yml
  core/src/epicli/data/common/defaults/configuration/applications.yml
  core/src/epicli/data/common/defaults/configuration/image-registry.yml
  core/src/epicli/data/common/defaults/configuration/rabbitmq.yml
  docs/home/howto/SECURITY.md
  docs/home/howto/UPGRADE.md
Labels: type/backport

#2043 [v0.8] Fix postgres hot_standby setting
  CHANGELOG-0.8.md
  core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/replication-Debian.yml
  core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/replication-RedHat.yml
  core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/replication-repmgr-Debian.yml
  core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/replication-repmgr-RedHat.yml
  core/src/epicli/data/common/defaults/configuration/postgresql.yml
  core/src/epicli/data/common/tests/spec/postgresql/postgresql_spec.rb
  docs/home/HOWTO.md
  docs/home/howto/DATABASES.md
Labels: area/postgres, area/testing, type/backport

#2044 [v0.8] Pgpool not showing Replication State
  CHANGELOG-0.8.md
  core/src/epicli/data/common/ansible/playbooks/postgresql.yml
  core/src/epicli/data/common/ansible/playbooks/roles/applications/templates/pgpool/02-configmaps.yml.j2
  core/src/epicli/data/common/ansible/playbooks/roles/postgresql/defaults/main.yml
  core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/configure-postgresql.yml
  core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/replication-repmgr-Debian.yml
  core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/replication-repmgr-RedHat.yml
  docs/home/howto/DATABASES.md
Labels: area/postgres, type/backport

#2054 Set LANG for testing curator_cli commands
  core/src/epicli/data/common/ansible/playbooks/roles/elasticsearch_curator/tasks/configure-cron-jobs.yml
Labels: area/logs

#2048 [Automated tests] Raise error when remote command fails
  core/src/epicli/data/common/tests/.rspec
  core/src/epicli/data/common/tests/Rakefile
  core/src/epicli/data/common/tests/spec/rabbitmq/rabbitmq_spec.rb
  core/src/epicli/data/common/tests/spec/zookeeper/zookeeper_helpers.rb
Labels: area/testing

#2047 Update test checking ownership of /etc/prometheus
  core/src/epicli/data/common/ansible/playbooks/roles/prometheus/tasks/install.yml
  core/src/epicli/data/common/tests/spec/prometheus/prometheus_spec.rb
Labels: area/monitoring, area/testing

#2055 Add GitHub issue template for releasing version
  .github/ISSUE_TEMPLATE/release-version.md
Labels: area/development

#2040 Support Azure RHEL LVM images
  CHANGELOG-0.10.md
  core/src/epicli/cli/engine/ApplyEngine.py
  core/src/epicli/cli/engine/providers/azure/InfrastructureBuilder.py
  core/src/epicli/cli/engine/terraform/TerraformFileCopier.py
  core/src/epicli/cli/engine/terraform/TerraformTemplateGenerator.py
  core/src/epicli/cli/helpers/build_saver.py
  core/src/epicli/cli/helpers/data_loader.py
  core/src/epicli/cli/helpers/os_images.py
  core/src/epicli/data/azure/defaults/infrastructure/cloud-init-custom-data.yml
  core/src/epicli/data/azure/defaults/infrastructure/virtual-machine.yml
  core/src/epicli/data/azure/terraform/infrastructure/cloud-init-custom-data/rhel/cloud-config.yml
  core/src/epicli/data/azure/terraform/infrastructure/virtual-machine.j2
  core/src/epicli/data/azure/validation/infrastructure/cloud-init-custom-data.yml
  core/src/epicli/data/common/tests/Rakefile
  core/src/epicli/data/common/tests/spec/common/common_helpers.rb
  core/src/epicli/data/common/tests/spec/common/common_spec.rb
  docs/home/HOWTO.md
  docs/home/howto/CLUSTER.md
Labels: provider/azure
