Repository hitachienergy/epiphany, pull requests merged in 2022-03, with the labels that each got.

#3045 Fix issue with expiring repository certificates on Azure on RHEL 7
  ansible/playbooks/roles/repository/tasks/RedHat/install-packages.yml
  docs/changelogs/CHANGELOG-2.0.md
Labels: type/bug, provider/azure, priority/medium, area/repository

#3043 [2.0] Fix doubled haproxy entries in prometheus.yml after upgrade
  ansible/playbooks/roles/prometheus/tasks/upgrade/main.yml
  docs/changelogs/CHANGELOG-2.0.md
Labels: type/bug

#3044 [1.3] Fix doubled haproxy entries in prometheus.yml after upgrade
  ansible/playbooks/roles/prometheus/tasks/upgrade/main.yml
  docs/changelogs/CHANGELOG-1.3.md
Labels: type/bug, type/backport
